name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex git \
            libelf-dev libssl-dev make python3 \
            device-tree-compiler cpio kmod \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Install Clang
        run: |
          wget https://github.com/ZyCromerZ/Clang/releases/latest/download/Clang-20.0.0.tar.gz
          mkdir clang
          tar -xf Clang-20.0.0.tar.gz -C clang --strip-components=1

      - name: Build Defconfig
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          make O=out ARCH=arm64 vendor/lito-perf_defconfig

      - name: Build Kernel
        run: |
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH

          make O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LD=ld.lld \
            -j$(nproc --all)

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dtb*
