name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ZerviOP/android_kernel_xiaomi_gauguin
          kernel-branch: lineage-23.2
          config: gauguin_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r563880c     
          anykernel3: true
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/tiann/KernelSU
          
